# Generated by Django 5.2.5 on 2025-09-08 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailingattempt_mailing"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.client",
                verbose_name="Клиент",
            ),
        ),
    ]
